// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOg0OV-x7wpY-fgMfZLealDq-7Wg7PZJk',
    appId: '1:672868290185:web:677e6520bf43fc14240058',
    messagingSenderId: '672868290185',
    projectId: 'qcutapp-2026',
    authDomain: 'qcutapp-2026.firebaseapp.com',
    storageBucket: 'qcutapp-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-Rse2Blr590TOMXRln7F9I-ayyT4EXak',
    appId: '1:672868290185:android:8884a90ed874f7b0240058',
    messagingSenderId: '672868290185',
    projectId: 'qcutapp-2026',
    storageBucket: 'qcutapp-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQSqXCEHPrTgkXr0mH_WTa85ev5bKX_-I',
    appId: '1:672868290185:ios:b39060bb8fa78b85240058',
    messagingSenderId: '672868290185',
    projectId: 'qcutapp-2026',
    storageBucket: 'qcutapp-2026.firebasestorage.app',
    iosBundleId: 'com.example.qcutapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQSqXCEHPrTgkXr0mH_WTa85ev5bKX_-I',
    appId: '1:672868290185:ios:b39060bb8fa78b85240058',
    messagingSenderId: '672868290185',
    projectId: 'qcutapp-2026',
    storageBucket: 'qcutapp-2026.firebasestorage.app',
    iosBundleId: 'com.example.qcutapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOg0OV-x7wpY-fgMfZLealDq-7Wg7PZJk',
    appId: '1:672868290185:web:2fc9e359e6e99344240058',
    messagingSenderId: '672868290185',
    projectId: 'qcutapp-2026',
    authDomain: 'qcutapp-2026.firebaseapp.com',
    storageBucket: 'qcutapp-2026.firebasestorage.app',
  );
}
